# Generated by Django 5.1.5 on 2025-01-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=256, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
        ),
    ]
